FROM nginx:latest 
# 表示该镜像是基于nginx:latest镜像构建的

COPY dist/  /usr/share/nginx/html/
# 表示将项目根目录下dist文件中所有内容复制到镜像中的/user/share/nginx/html/目录下,在nginx的default.conf配置文件中也可看到相关路径配置

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# 表示将 nginx 目录下的 default.conf 文件复制到 etc/nginx/conf.d/default.conf，用本地的 default.conf 配置来替换 Nginx 镜像里的默认配置。